### ISSUE TITLE
acdcloud

### ISSUE THREAD

**Issue by fbartels** [cschomburg/dotfiles#1]
Hi,

I was just strolling through github for some inspiration for https://github.com/fbartels/mount-encfs-cloud and noticed you have a slightly modified version of my script in your repo. Just wanted to drop by and say "Hi" and notify that I also have added some more rclone switches to my script (upload and mount with rclone).

Greetings from Hanover to Hanover ;-)

**Comment by cschomburg** [comment]
Hey,

Thanks for your script, it's probably the best out there! Made my dive into ACD+encfs much more pleasant. Rclone support is very nice to have, because my initial reaction was to combine both of your scripts into a single one. Also noticed that I forgot proper attribution in my version, which you definitely deserve.

Though I have to admit that I'm now using pure rclone with its builtin encryption :)

Cheers! Currently chasing the last bits of summer in Las Palmas before returning to Hanover for christmas :)
